---
name: Package-Rename
version: 0.01
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Rename or copy package
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
recommends:
  perl: 5.01
provides:
  Package::Rename:
    file: lib/Package/Rename.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
